CREATE TABLE Alunos (
    id_aluno NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    status VARCHAR2(100) NOT NULL,
    data_ingresso VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_aluno PRIMARY KEY (id_aluno)
);

ALTER TABLE alunos
MODIFY email UNIQUE;

ALTER TABLE Alunos
ADD CONSTRAINT ck_status
CHECK (status IN ('ATIVO', 'TRANCADO', 'FORMADO')); 

CREATE TABLE Professores (
    id_professor NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    salario DECIMAL(10,2) NOT NULL,
    CONSTRAINT pk_professor PRIMARY KEY (id_professor)
);

ALTER TABLE alunos
MODIFY email UNIQUE;

CREATE TABLE Disciplinas (
    id_disciplina NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(100) NOT NULL,
    carga_horaria NUMBER(10) NOT NULL,
    CONSTRAINT pk_disciplina PRIMARY KEY (id_disciplina)
);

CREATE TABLE Turmas (
    id_turma NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_disciplina NUMBER(10) NOT NULL,
    id_professor NUMBER(10) NOT NULL,
    limite_vagas NUMBER(10) NOT NULL,
    semestre VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_turma PRIMARY KEY (id_turma),
    CONSTRAINT fk_turma_professor FOREIGN KEY(id_professor) REFERENCES Professores (id_professor),
    CONSTRAINT fk_turma_disciplina FOREIGN KEY(id_disciplina) REFERENCES Disciplinas (id_disciplina)
);

CREATE TABLE Matriculas (
    id_matricula NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_turmas NUMBER(10) NOT NULL,
    id_aluno NUMBER(10) NOT NULL,
    data_matricula VARCHAR2(100),
    situacao VARCHAR2(100),
    nota_final DECIMAL(10,2),
    CONSTRAINT pk_matricula PRIMARY KEY (id_matricula),
    CONSTRAINT pk_matricula_turma FOREIGN KEY(id_turmas) REFERENCES Turmas (id_turma),
    CONSTRAINT pk_matricula_aluno FOREIGN KEY(id_aluno) REFERENCES Alunos (id_aluno)
);

ALTER TABLE Matriculas
ADD CONSTRAINT ck_situacao
CHECK (situacao IN ('APROVADO', 'REPROVADO', 'CURSANDO'));